### ISSUE TITLE
Becca making GitHubs for the sake of making GitHubs?

### ISSUE THREAD

**Issue by ebeshero** [RJP43/STD_UPG#1]
At issue: Is Becca Parker creating Repos because she can? Or because it's Always Better to use GitHub? Discuss.

**Comment by RJP43** [comment]
I created this repo. in place of doing a Google Doc for the the Conference Round Table presentation (like what we will be using for the Jane Austen Round Table) and also hoping it will make things easier for sharing files, ideas,  and meeting times because yes! GitHub is ALWAYS better wheb collaborating on digital texts/code :)

**Comment by RJP43** [comment]
Also, we can create a GitHub webpage from this repo. for any on the web material we wish to share at conference.

**Comment by ebeshero** [comment]
Huzzah! Good, and yes, this makes eminent sense.
