### ISSUE TITLE
Mapping out Conference Presentation --- Minneapolis

### ISSUE THREAD

**Issue by alexkrongel** [RJP43/STD_UPG#5]
75 minutes ———2-3:15

3-5 minutes of coding 
babushka dolls and trees

pull out poem - lets all mark it up together
make them describe the elements of a poem, describe the structure of the poem

xml comparison 
-why make these decisions about hierarchy? 
show how we did it and talk about overlying hierarchy and what we choose to privilege 
- then features of the text
  (mention schemas here, and show how our projects use schema)

xslt - use xpath to navigate the structure we have 

and produce visually different pages 
comparison of pages 

end - what we are capable of
http://dickinson16.newtfire.org/1603.html

Ok -

**Comment by andrewntz23** [comment]
Broadly throughout the whole presentation:

Elisa will cover major points of the kind of projects we do: XML, how we process them, etc. 

-Begin with some coding. Discuss some features of XML: how it is at basis of microsoft (.docx), give introduction to XML with basic syntax / structure, including some intentional errors. 

-get right into marking up the poem with the audience; mark it up taking audience participation into account.
    -Describe the structure of document.
    -Describe aspects of the text of the poem itself

-move onto Alex vs. Becca markup strategies: What’s more important in each? What was given precedence? What is gained / lost in each scenario?
    -Use of attributes in Alex version versus giving precedence to the sentence in       Becca’s

Visualizing Research
    -Move on to our XSLT / HTML / CSS 
    -Still need to develop the SVG
Highlight 

We would like Brooke to talk about the Dickinson project at the conclusion - in particular focus on one particular poem, and the different versions. How doing this kind of research can allow us to quickly analyze the differences, etc. 

IMPORTANT:

Creating the SVG is the only remaining coding that we need to do, which we can knock out in the morning

**Comment by ebeshero** [comment]
Agreed--Andrew's outline is very helpful! :+1:

**Comment by RJP43** [comment]
@blawrence719 check this out when you get a moment and we will meet up after you are done with the leadership workshop to have a run through the whole thing together. We are going to check out the room here a little bit... it is supposedly a very large space so would be good to practice in there if we can. I will keep you posted.
